### ISSUE TITLE
Let user decide logging.properties level

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/project-keeper-maven-plugin#34]
## Problem

The project keeper rewrites the level of logging.properties to ALL:
java.util.logging.ConsoleHandler.level=ALL
com.exasol.level=ALL

Sometimes we want to have another level there. It would be nice if the keeper doesn't rewrite them.

**Comment by redcatbear** [comment]
:+1:

**Comment by jakobbraun** [comment]
Not sure if it is a good idea to change this. This file enforces ALL log messages so that in the test all closures are captured by jacoco. As far as I can see it would be good to have this for all projects.

Maybe you could simply use a diffrent file for testing with UI?
Or is there a specific reason why you need a different config?

**Comment by redcatbear** [comment]
I think I mixed that up with the messages the testcontainer produces. I always set those back to info, since except for debugging all they produce is clutter. And those have no impact on test coverage.

I agree with your statement about test coverage for regular log messages **our** code produces. Which are the ones in question in this issue.
